### ISSUE TITLE
Use Plotly with tooltips for all the plots

### ISSUE THREAD

**Issue by ddil-projects** [de-data-lab/WRK#57]
Some graphs have pop-ups and others don't. If you can make them all have hover pop-up boxes, then I would recommend removing the grids in the back and making it a blank/white background instead of the grid.

**Comment by nsunami** [comment]
I'm separating the issue about the grid line into #65. 

I'm also creating separate issues for each tab:

1. https://github.com/de-data-lab/WRK/issues/66
2. https://github.com/de-data-lab/WRK/issues/67
3. https://github.com/de-data-lab/WRK/issues/68
4. https://github.com/de-data-lab/WRK/issues/69

Let's continue tracking the issue in the separate issues. Closing this for now.
